// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectAPI;

#nullable disable

namespace ProjectAPI.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20240211093933_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectAPI.Models.Project", b =>
                {
                    b.Property<Guid>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Date")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("_date");

                    b.Property<int?>("TemperatureAfternoon")
                        .HasColumnType("integer")
                        .HasColumnName("temp2");

                    b.Property<int?>("TemperatureMorning")
                        .HasColumnType("integer")
                        .HasColumnName("temp1");

                    b.Property<string>("Weather")
                        .HasColumnType("text")
                        .HasColumnName("meteo");

                    b.Property<string>("WorkAt")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("travail");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("text")
                        .HasColumnName("horaires");

                    b.HasKey("GUID")
                        .HasName("projet_pk");

                    b.ToTable("projet");
                });
#pragma warning restore 612, 618
        }
    }
}
